# Generated by Django 5.0.7 on 2024-07-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentID', models.IntegerField(default=0)),
                ('StudentRoll', models.IntegerField(default=0)),
                ('Class', models.CharField(max_length=100)),
                ('Shift', models.CharField(max_length=100)),
                ('StudentsName', models.CharField(max_length=100)),
                ('FatherName', models.CharField(max_length=100)),
                ('MotherName', models.CharField(max_length=100)),
                ('Mobile', models.IntegerField()),
                ('Gender', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Address', models.TextField()),
            ],
        ),
    ]
